### ISSUE TITLE
lstlean.tex

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover-community/lean#109]
Is [lstlean.tex](https://github.com/leanprover-community/lean/blob/master/extras/latex/lstlean.tex) in this repo the most up-to-date version of this file? I have accumulated some local changes over time, should I make a PR to add them to this file?

**Comment by robertylewis** [comment]
See #110; if you have more additions please add them there! (I just noticed this issue.)

**Comment by bryangingechen** [comment]
Closing this as I think the changes were added in #133.
