### ISSUE TITLE
olean timestamps

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/lean#112]
Lean uses timestamps to check the validity of olean files, which causes trouble with some of the scripts that distribute oleans: the timestamps can get mangled and cause recompilation.

I did some quick experiments with this setup, where `a --> b` means `a.lean imports b.lean`:

`three --> two --> one`

I built all .olean files, then touched `one.olean`. Running `lean three.lean` recompiled `two.lean`, since the timestamp of `one.olean` is newer than that of `two.olean`.
Then I touched `one.lean`. Running `lean three.lean` recompiled `one.lean`, since the timestamp of `one.lean` is newer than that of `one.olean`. (It also recompiled `two.lean` of course.)

Naively, one of these checks should be easy to get rid of. Instead of comparing the timestamps of `one.lean` and `one.olean`, could we store the file hash of `one.lean` in the olean file? `one.olean` would be valid for `one.lean` iff the hashes match. This way, the lean files could have newer timestamps without causing issues.

The other one I'm less sure about. oleans know their direct imports, right? Could they store hashes of the oleans they import for the same kind of comparison?

Note: I'm not actually sure which kind of comparison causes the trouble with `cache-olean`/`update-mathlib`, or if both do.

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by gebner** [comment]
> Instead of comparing the timestamps of one.lean and one.olean, could we store the file hash of one.lean in the olean file?

Yes, this shouldn't be too hard.  A nice side-effect would be that if you modify a file accidentally, you could just change it back and you don't need to recompile everything.

We need to be a bit careful with line endings on windows though.  Lots of stuff seems to mess with them.  IIRC vscode likes to change them when it sends the files to the lean server.  Maybe git also changes them?

> Note: I'm not actually sure which kind of comparison causes the trouble with cache-olean/update-mathlib, or if both do.

We could also change cache-olean/update-mathlib to use the current timestamp when unpacking archives.

**Comment by Kha** [comment]
Why not cache the .olean contents (module modifications, transitively) instead? That would also be resistant against other minor changes, though none that e.g. change declaration file positions.

**Comment by digama0** [comment]
@Kha The olean files are already hashed. But this doesn't help if you want to determine if the olean is out of date with respect to the lean file.

**Comment by Kha** [comment]
Yeah, I shouldn't comment while ski lifting... I guess what I was thinking of was to actually make use of that hash to avoid rebuilding B.olean when a trivial change in A.lean led to the same A.olean. But implementing that may not be worth the trouble if that situation rarely arises with the current .olean format.

**Comment by kbuzzard** [comment]
A gotcha that happened to me today: if you upgrade a Lean project which uses mathlib from 3.4.2 to 3.5.1 then update-mathlib doesn't see anything that needs changing (it might reuse old cached olean files, for example) but I suspect that the files need to be recompiled anyway because the version of Lean changed.

**Comment by robertylewis** [comment]
> A gotcha that happened to me today: if you upgrade a Lean project which uses mathlib from 3.4.2 to 3.5.1 then update-mathlib doesn't see anything that needs changing (it might reuse old cached olean files, for example) but I suspect that the files need to be recompiled anyway because the version of Lean changed.

You can't do this without also calling `leanpkg upgrade` (and getting a fresh mathlib). There will never be an olean cache of a 3.4.2-era mathlib built with 3.5.1.

**Comment by Vtec234** [comment]
I can take a stab at this tomorrow if noone has started on it yet. By "this", I mean a MVP of:
- storing the hash of x.lean in x.olean (bytewise for now, normalizing line endings can be added later)
- storing the hashes of olean imports of y in y.olean to avoid recompilation

**Comment by jcommelin** [comment]
@Vtec234 Also see https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/new.20mathlib.20tools/near/189599261

**Comment by Vtec234** [comment]
The hashing has been merged, can this be closed?
