### ISSUE TITLE
leanpkg lean_version bug

### ISSUE THREAD

**Issue by PatrickMassot** [leanprover-community/lean#126]
See discussion at https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/default.20toolchain

`elan default leanprover-community-lean-3.5.1`
works as intended, as can be seen from `lean --version` ran outside a project. But then `leanpkg new test_proj` has a buggy `leanpkg.toml` where the `lean_version` field is not the expected `leanprover-community:lean-3.5.1`.

**Comment by TwoFX** [comment]
FWIW, here are two ways to tackle this:

**Option 1**: Revert f2acb66b6db96e7a3e1e7aab42c2e8c251a3efc1, and change `leanpkg/lean_version.lean` like this:
```diff
diff --git a/leanpkg/leanpkg/lean_version.lean b/leanpkg/leanpkg/lean_version.lean
index 8f91c205d..1fde25382 100644
--- a/leanpkg/leanpkg/lean_version.lean
+++ b/leanpkg/leanpkg/lean_version.lean
@@ -11,7 +11,7 @@ sformat!("{major}.{minor}.{patch}")
 
 def lean_version_string :=
 if lean.is_release then
-    lean_version_string_core
+    "leanprover-community/lean:" ++ lean_version_string_core
 else if lean.special_version_desc ≠ "" then
     lean.special_version_desc
 else
```
This simply adds the correct prefix to the lean version that `leanpkg` knows.

**Option 2**: Revert f2acb66b6db96e7a3e1e7aab42c2e8c251a3efc1, and change `src/CMakeLists.txt` like this:
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 207071eab..bbd04467b 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -6,8 +6,8 @@ project(LEAN CXX C)
 set(LEAN_VERSION_MAJOR 3)
 set(LEAN_VERSION_MINOR 6)
 set(LEAN_VERSION_PATCH 0)
-set(LEAN_VERSION_IS_RELEASE 1)  # This number is 1 in the release revision, and 0 otherwise.
-set(LEAN_SPECIAL_VERSION_DESC "" CACHE STRING "Additional version description like 'nightly-2018-03-11'")
+set(LEAN_VERSION_IS_RELEASE 0)  # This number is 1 in the release revision, and 0 otherwise.
+set(LEAN_SPECIAL_VERSION_DESC "leanprover-community/lean:${LEAN_VERSION_MAJOR}.${LEAN_VERSION_MINOR}.${LEAN_VERSION_PATCH}" CACHE STRING "Additional version description like 'nightly-2018-03-11'")
 set(LEAN_VERSION_STRING "${LEAN_VERSION_MAJOR}.${LEAN_VERSION_MINOR}.${LEAN_VERSION_PATCH}")
 if (LEAN_SPECIAL_VERSION_DESC)
   set(LEAN_VERSION_STRING "${LEAN_VERSION_STRING}-${LEAN_SPECIAL_VERSION_DESC}")
```
This changes the Lean "special version" to be of the form `leanprover-community/lean:3.6.0` and unsets the release flag. `leanpkg` will then use this special version string as the lean version. This will also change the output of `lean --version` like this:
```
Lean (version 3.6.0, leanprover-community/lean:3.6.0, commit b764d8a092d6, Release)
```

`leanpkg new` creates correct `leanpkg.toml` in both cases. I think the second option is the more elegant, but I don't know whether either of the options breaks something elsewhere.

**Comment by gebner** [comment]
> Option 1

I think that's the best option.  @robertylewis You wrote the original fix, what do you think?

**Comment by Kha** [comment]
@TwoFX Great analysis! I'm not really involved, but I like option 2 as well.

**Comment by Kha** [comment]
Ah... :)

**Comment by Kha** [comment]
Ok, after taking a closer look, I don't see any issues with option 1. Option 2 is a bit nicer *if* you want `lean --version` to change, but it should be amended so that `IS_RELEASE` doesn't have to be changed to `0`.

**Comment by robertylewis** [comment]
> I think that's the best option. @robertylewis You wrote the original fix, what do you think?

Oops, sorry, I forgot to answer this yesterday. I agree option 1 looks good!

**Comment by TwoFX** [comment]
Alright, since the first seems to the be preferred, I have created a PR for it at #131.
