### ISSUE TITLE
Lean API for creating mutually inductive and nested inductive types

### ISSUE THREAD

**Issue by cipher1024** [leanprover-community/lean#14]

**Comment by cipher1024** [comment]
Next step:
 * [ ] test interface with QPF-based data types

**Comment by khoek** [comment]
(Just so it's written somewhere) parsing but no definition-creating: https://github.com/leanprover/lean/blob/master/library/init/meta/interactive_base.lean#L196 happens to already be in core lean, declared directly next to the implementation of the `inductive` keyword in https://github.com/leanprover/lean/blob/master/src/frontends/lean/inductive_cmds.cpp#L714.

**Comment by cipher1024** [comment]
Thanks for the note! That feature is very useful for the QPF package. I'd love to see the same for `def`.
