### ISSUE TITLE
lean::optional might be buggy

### ISSUE THREAD

**Issue by Vtec234** [leanprover-community/lean#154]
Sebastien Gouezel has noted on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/mathlib.20is.20on.203.2E7!/near/191181967) that the Windows version of Lean 3.7.1 needlessly recompiles all .oleans (including stdlib). ~I have identified the cause of this to be [this line](https://github.com/leanprover-community/lean/blob/cd04429aebcbcc14e26fa5204c5365dfebc5fde9/src/library/module_mgr.cpp#L465) in `module_mgr.cpp`, where the `*src_hash == *olean_src_hash` check fails even though it shouldn't. Some of our [build logs](https://ci.appveyor.com/project/cipher1024/lean/builds/31505936/job/c55wwrhd3sn1via1?fullLog=true#L803) actually caught this issue as the value part of `optional<unsigned> src_hash` being uninitialized. Now, to my best knowledge the variable is actually [initialized](https://github.com/leanprover-community/lean/blob/cd04429aebcbcc14e26fa5204c5365dfebc5fde9/src/library/module_mgr.cpp#L449) correctly as per  [`std::optional`](https://en.cppreference.com/w/cpp/utility/optional), pointing to UB in the implementation of `lean::optional`. This hypothesis is supported by swapping out `lean::optional` for `std::optional`, which fixes the bug.~

Fixing ~this~ warnings due to `lean::optional` unfortunately looks quite problematic. The ideal solution would be to use `std::optional` everywhere, but it's supported only in C++17, so we would have to drop `g++-4.9` builds and update to GCC 7 or newer. Is testing on the old compilers needed for anything? Alternatively, use C++14 and [`std::experimental::optional`](https://stackoverflow.com/a/17013985), but this is likely to cause issues cross-platform

A second way out would be to fix `lean::optional`. I am not enough of a C++ standard wizard to do this confidently, but splicing in an implementation of `std::optional` from the GCC libstdc++ headers might just work.

Finally, I think we should consider building with `-Werror` or at least `-Werror=some-warning` for warnings which are likely to indicate UB like `maybe-uninitialized`. While the warning appears in build logs, it doesn't do so when I build Lean locally - with `-Werror`, I would've caught this issue earlier.

**Comment by Vtec234** [comment]
Oh, I've just realized .oleans are [opened](https://github.com/leanprover-community/lean/blob/master/src/library/module.cpp#L584) in text mode, which is more likely to be the cause. I'm still not confident about `optional`, but it can be dealt with separately.

**Comment by gebner** [comment]
I'm completely happy to drop support for ancient compilers.  We distribute statically-linked binaries, these should still run on old distributions even if we compile using a newer compiler.

As long as you update the compiler version, make sure CI still works on all platforms, and that the resulting binaries still run, I'm happy to merge such a change.

We can also switch to github actions if you want.  (Travis times out all the time, and appveyor sometimes takes a day before it even starts building.)

> `-Werror`

I'm not a big fan of `-Werror`, it causes unexpected breakage.  For example, when travis updates the compiler version.

For the warnings about unintialized fields in `optional`: we've known about them for a long time and there haven't been any issues.  We would have probably just disabled the warning.

**Comment by Vtec234** [comment]
Fixed in #155 .
