### ISSUE TITLE
Drop support for ancient compilers and move to GitHub Actions

### ISSUE THREAD

**Issue by Vtec234** [leanprover-community/lean#156]
Our current CI is super slow, especially on AppVeyor Windows which often takes on the order of 24 hours to start building. My experience with Actions so far has been pretty positive (it tends to start instantaneously), so we can hope moving to them from Travis+AppVeyor would speed up the process.

While doing so, we could also drop support for GCC 4.9 and Clang 3.5, as these are rather old and don't support modern C++ standards. A good conservative choice should be GCC 7 and Clang 6, which are the versions in Ubuntu 18.04LTS.

See also the discussion in #154.

**Comment by EdAyers** [comment]
I'm having a half-baked attempt at this here: 
https://github.com/EdAyers/lean/tree/github_actions

**Comment by EdAyers** [comment]
Currently it can build on all of the platforms but some of the tests are failing in mac and windows. It also needs to perform tests for emscripten and emit artefacts for windows. I haven't added any workflows for releasing. Additionally, if both the mac and ubuntu builds succeed it should attempt to pull and build mathlib.

**Comment by gebner** [comment]
> Additionally, if both the mac and ubuntu builds succeed it should attempt to pull and build mathlib.

I don't think we should build mathlib in CI.  1) This takes really long.  2) Most PRs break mathlib on purpose.

**Comment by gebner** [comment]
On the other hand, pushing releases is *really* important.  The current CI does the following: if it builds a tag, then it adds the generated binaries as files to the github release.  https://github.com/leanprover-community/lean/blob/f2b0c28ed6634fdb45c405650f501e5a7226c2e5/.travis.yml#L218-L229

**Comment by EdAyers** [comment]
So the release zip should contain the files matching `build/lean-*`. Am I reading this right?

**Comment by EdAyers** [comment]
How about it tries to build mathlib only when we have a release build?

**Comment by bryangingechen** [comment]
> How about it tries to build mathlib only when we have a release build?

We usually fix up mathlib in a PR shortly after the release, so I don't think that would be useful either.

**Comment by bryangingechen** [comment]
> So the release zip should contain the files matching `build/lean-*`. Am I reading this right?

I think the zip file is named something that matches `build/lean-*`. I think the ZIP file itself is generated by cmake, see the bottom of [this file](https://github.com/leanprover-community/lean/blob/da007abd30e1e23de9cacda207a20d67510301a3/src/CMakeLists.txt).

**Comment by EdAyers** [comment]
Ok, I've got it to make the lean-* artefacts and it builds and tests correctly on all platforms. There still needs to be some work adding release artifacts, which are different to the github actions artifacts.

**Comment by gebner** [comment]
This was merged in #218.
