### ISSUE TITLE
Changes to the core library

### ISSUE THREAD

**Issue by urkud** [leanprover-community/lean#160]
Let's track here what should be changed in the core library. I start with a list of simple modifications.

* [x] redefine `prod.map` as `λ p, (f p.1, f p.2)`;
* [x] redefine `uncurry` as `λ f p, f p.1 p.2`;
* [x] use `export inhabited (default)` instead of `def`;
* [x] generalize many lemmas about fields to `division_ring`, and some lemmas about `discrete_linear_ordered_field` to `linear_ordered_field`, or move the whole `division_ring`/`field` theory to `mathlib`, and do it there.

**Comment by kbuzzard** [comment]
I would vote for getting as much maths out of core as possible. Updating core Lean is a pain for people like the CoCalc people. Our tooling works on CoCalc so you can have any version of mathlib you like, but we can't control which version of Lean they use, and every time mathlib stops supporting Lean version n-1 you can't use mathlib master in CoCalc until they upgrade, which they have made it clear they don't want to do very often.

**Comment by gebner** [comment]
> I would vote for getting as much maths out of core as possible. Updating core Lean is a pain for people like the CoCalc people.

This is a big CoCalc problem.  They should really use elan.  You can install elan system-wide.  And if you pre-seed every user with a `.elan` directory containing all available Lean versions (you can just put symlinks to a system-wide installation) then it doesn't require any internet connection.

> Our tooling works on CoCalc so you can have any version of mathlib you like, [...]

Well, only mathlib versions that work with the Lean version installed on CoCalc.  And current mathlib only supports the current Lean version.  I don't think we will ever have backwards-compatibility with old Lean versions.  We want to make use of the latest bug fixes/features in Lean.

Is there any way we can help out with moving CoCalc to a sensible Lean set up?

**Comment by robertylewis** [comment]
> Is there any way we can help out with moving CoCalc to a sensible Lean set up?

IIRC, one of the big complications is that basic (free) CoCalc accounts don't have internet access. So you can't count on elan being able to download new versions of Lean.

**Comment by gebner** [comment]
> IIRC, one of the big complications is that basic (free) CoCalc accounts don't have internet access. So you can't count on elan being able to download new versions of Lean.

My point is that is easy to preload elan with all previous versions of Lean.  There's no reason CoCalc needs to be restricted to a single Lean version.

**Comment by eric-wieser** [comment]
I don't think there's any point keeping this open now, we can jut create new issues.
