### ISSUE TITLE
Generalise tactic combinators

### ISSUE THREAD

**Issue by JLimperg** [leanprover-community/lean#206]
Many of the tactic combinators could be generalised. E.g.:

```lean
try : tactic unit -> tactic unit
-- could be tactic α -> tactic (option α) (see try_core)

all_goals : tactic unit -> tactic unit
-- could be tactic α -> tactic (list α)

focus : list (tactic unit) -> tactic unit
-- could be list (tactic α) -> tactic (list α)
```

Is there any reason not to generalise them? If not, I'll prepare a PR.

**Comment by gebner** [comment]
There is no reason that prevents us from generalizing them.  Please note that Lean 4 is apparently going the other way around: https://github.com/leanprover/lean4/pull/133

That is, combinators are only defined for `PUnit` wherever possible.  I kind of like that `do a; b` is a hard error now if `a` doesn't return unit.  However `(*>)` has the type `m PUnit → m α → m α` now! :scream:

**Comment by digama0** [comment]
These are not strict generalizations, because they don't return unit even if the input is unit. So they would have to have different names. Especially for something like `focus`, you don't want to construct and discard a superfluous list of units, so these specializations usually exist anyway, e.g. `list.mmap` vs `list.mmap'`.

**Comment by Kha** [comment]
>  I kind of like that `do a; b` is a hard error now if `a` doesn't return unit. However `(*>)` has the type `m PUnit → m α → m α` now! scream

@gebner Well, my thinking on the latter part was "let's see what breaks when I do the straightforward change... huh, nothing". Do you have a compelling example where this matters?

**Comment by gebner** [comment]
No, I don't have a compelling example where it would come in handy.  I was just *very* surprised when I saw this.  Lean 4 tries to copy everything from other languages including the naming convention, and then `(*>)` is [completely different](https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#v:-42--62-).

**Comment by Kha** [comment]
We often take Haskell as initial inspiration but do readily depart from it if there's no reason not to except for "Haskell does it this way". I'm pretty sure that if do-notation was implemented in GHC today, the `do a; b` warning would become a hard error. Would `*>` change as well? Not sure. @sgraf812 thoughts?

**Comment by digama0** [comment]
In `do a; b` there is the easy alternative `do _ <- a; b` to ignore the result, but for `*>` there is no similarly easy alternative unless you stick in those ugly `ignore` calls a la ML.

**Comment by Kha** [comment]
Just to spell it out, the reason for changing the type of `*>` was to keep `do a; b` being syntax sugar for `a *> b` (which actually wasn't quite true before).

**Comment by digama0** [comment]
What about `a >> b`? Currently those two are synonymous, are they going to be different now? I would be more comfortable with `a >> b` having type `m unit -> m A -> m A` and `a *> b` having `m A -> m B -> m B`. For me `*>` is explicitly about ignoring the result of one of the sides.

**Comment by Kha** [comment]
`>>` is actually completely different now, Leo reused it for non-monadic forward composition: https://github.com/leanprover/lean4/blob/master/src/Init/Core.lean#L349. It's used in the new parser, for example.

I wouldn't say that `*>` is always about throwing away a result - it's most prevalent in cominatoric parsers like `atom "(" *> expr <* atom "("`, where I *could* imagine someone wanting an error message if they accidentally threw away something that wasn't `()`. But that probably isn't the majority opinion, yeah. I don't really want to introduce a `seqRight' : m Unit -> ...`, so perhaps the best solution is to do an *early type-check* `a : m Unit, b : m B |- do a; b` in the new frontend, then desugar to the general `*>`. We can revert its type then as soon as the old frontend is gone.

**Comment by JLimperg** [comment]
I don't think the Lean4 changes have much bearing on the suggested tactic combinators change. Lean4 changes the types of combinators which *must* throw stuff away so that the throwing-away doesn't occur implicitly. The tactic combinators, on the other hand, *don't need to* throw away the results of the inner tactic, but they currently do. The motivation for this issue is that I actually have a problem where I want to apply a tactic to all goals and collect the results of these applications.

> These are not strict generalizations, because they don't return unit even if the input is unit. So they would have to have different names. Especially for something like `focus`, you don't want to construct and discard a superfluous list of units, so these specializations usually exist anyway, e.g. `list.mmap` vs `list.mmap'`.

Indeed. Here are some ways to address this:

(1) Only provide the 'informative' versions; if users want to throw away the result, they need to do so manually.
```lean
focus : list (tactic α) -> tactic (list α)
-- User can write `focus xs >> skip` (or `discard (focus xs)` in Lean4) if they need a `tactic unit`.
```

(2) Provide both the informative and non-informative variants. Then we have two follow-up questions:

(2.1) Naming: (a) We keep the current names and add `focus'` etc. for the informative variants. (b) The other way around. (a) avoids breakage; (b) avoids inconsistency with `mmap` vs `mmap'`.
```lean
-- (a)
focus : list (tactic unit) -> tactic unit
focus' : list (tactic α) -> tactic (list α)

-- (b)
focus : list (tactic α) -> tactic (list α)
focus' : list (tactic unit) -> tactic unit
```

(2.2) Implementation of non-informative variants: (a) We implement the non-informative variants in terms of the informative ones, by just throwing the result away. (b) We implement the informative and non-informative variants independently. (a) avoids copy-pasta; (b) avoids redundant work building lists of units.

```lean
-- (a)
focus : list (tactic α) -> tactic (list α) := ...
focus' : list (tactic unit) -> tactic unit := λ xs, focus xs >> skip

-- (b)
focus : list (tactic α) -> tactic (list α) := ...
focus' : list (tactic unit) -> tactic unit := ...
```

I have no particular preference for any of these designs; just tell me which one you want and I'll implement it. ;)

**Comment by sgraf812** [comment]
>  I'm pretty sure that if do-notation was implemented in GHC today, the do a; b warning would become a hard error. Would *> change as well? Not sure. @sgraf812 thoughts?

@Kha I agree about the `do a; b` change. I'm however not so sure about restricting the type of `*>`. I don't think that the former has to desugar directly to the latter.

Thinking in terms of GHC's `-XRebindableSyntax`, I'd probably want to give the function that `do a; b` desugars to a separate name. Although that means that `do _ <- a; b` desugars to yet another function. That function can't be `>>=` if something like `-XApplicativeDo` is not off the table for Lean...

As I said, I'm not sure, but maybe my line of thought helps you come to a conclusion.

**Comment by Kha** [comment]
@sgraf812 Thanks for your input, now I agree slightly more strongly that `*>`'s type should, eventually, be reverted. Lean 3 actually has rebindable syntax for `do` by default, but Lean 4 does not right now because that really is the opposite of hygiene... I also don't think it is likely something like `ApplicativeDo` will make it into the stdlib, but the great thing about Lean 4 is that it enables users to implement such variations on built-in syntax themselves, of course.
