### ISSUE TITLE
add_mul_self_eq

### ISSUE THREAD

**Issue by kckennylau** [leanprover-community/lean#232]
https://github.com/leanprover-community/lean/blob/master/library/init/algebra/ring.lean#L235

```lean
  lemma add_mul_self_eq (a b : α) : (a + b) * (a + b) = a*a + 2*a*b + b*b :=
  calc (a + b)*(a + b) = a*a + (1+1)*a*b + b*b : by simp [right_distrib, left_distrib]
               ...     = a*a + 2*a*b + b*b     : by rw one_add_one_eq_two
```

This is placed in the `comm_ring` section, but in fact it is true for any `comm_semiring`.

**Comment by digama0** [comment]
why is this an issue instead of a PR? The change itself is trivial and you have indicated what it is.

**Comment by kckennylau** [comment]
mainly because I don't know how to test things locally

**Comment by bryangingechen** [comment]
I've just invited you to this repo so you can now rely on github actions to test things.

**Comment by kckennylau** [comment]
how does this work?

**Comment by bryangingechen** [comment]
If you make a branch from this repo (and not your own external fork), then github actions will run on each pushed commit. (Similar to how things work in mathlib).
