### ISSUE TITLE
io.fs.get_char only takes every fourth character

### ISSUE THREAD

**Issue by jasonrute** [leanprover-community/lean#274]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [X] Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * I searched for `get_char` and nothing came up
    * [X] Reduced the issue to a self-contained, reproducible test case.

### Description

In the limited tests I've done, `io.fs.get_char` returns every forth character instead of every character.  It is clearly a bug at least for my setup.

However, it also doesn't seem like a high priority since I doubt anyone uses this function.

### Steps to Reproduce

```
import system.io

meta def main : io unit := do
  child ← io.proc.spawn {
    cmd := "echo",
    args := ["0123456789012345678901234567890"],
    stdout := io.process.stdio.piped
  },
  c1 <- io.fs.get_char child.stdout,
  c2 <- io.fs.get_char child.stdout,
  c3 <- io.fs.get_char child.stdout,
  c4 <- io.fs.get_char child.stdout,
  c5 <- io.fs.get_char child.stdout,
  io.run_tactic (tactic.trace (repr [c1, c2, c3, c4, c5]))

example : 1=1 := begin
 tactic.unsafe_run_io main
end
```

Run in vs-code or via the command line (using `lean <file>.lean` or `lean --run <file>.lean`.

**Expected behavior:** [What you expect to happen]

Should print/trace `['0', '1', '2', '3', '4']`.  It should take the first 5 characters.

**Actual behavior:** [What actually happens]

Does print/trace `['0', '4', '8', '2', '6']`.  It is only taking every 4th character.

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time.

### Versions

Lean (version 3.13.1, commit ba05c95629d4)
MacOS 10.14.6

### Additional Information

Here is the [implementation of `get_char`](https://github.com/leanprover-community/lean/blob/194cc8e2416b5969cfdab4006bb9e20cb75e5adc/library/system/io.lean#L156).  I don't see what is wrong.  Maybe one needs to look at [the C++ code](https://github.com/leanprover-community/lean/blob/303d31f1f1e4af8727761098b43dbe59d7c67d64/src/library/vm/vm_io.cpp#L353) for `io.fs.read`.

`io.fs.get_line` and `io.fs.read_to_end` seem to work fine in the limited tests I've done.

Again, I don't think this is a high priority, but I think it is clearly a bug.

**Comment by jasonrute** [comment]
Ok, I think it is a unicode thing.  If I use "¬(α→β)∨δ∧ε" (in place of "0123...", then I get `['¬', '±', 'β', '', '∧']`.

**Comment by digama0** [comment]
I expect it is reading four byte `int`s from the stream. Does `read` work to give you the entire `char_buffer`, or are bytes missing there too?

**Comment by digama0** [comment]
Hm:
```

#eval do
  child ← io.proc.spawn {
    cmd := "echo",
    args := ["0123456789012345678901234567890"],
    stdout := io.process.stdio.piped
  },
  c1 <- io.fs.read child.stdout 2,
  c2 <- io.fs.read child.stdout 2,
  io.run_tactic (tactic.trace (c1, c2)) -- ([0, 1], [8, 9])
 ```
It appears that getting a buffer works correctly but the seeking that happens after that is 4 times larger than it should be

**Comment by digama0** [comment]
And with unicode:
```lean
meta def test (s : string) := do
  child ← io.proc.spawn {
    cmd := "echo",
    args := [s],
    stdout := io.process.stdio.piped
  },
  c1 <- io.fs.read child.stdout 2,
  c2 <- io.fs.read child.stdout 2,
  io.run_tactic (tactic.trace (c1, c2))

#eval test "0123456789" /- 1 byte UTF8 -/ -- ([0, 1], [8, 9])
#eval test "áéóúåø"     /- 2 byte UTF8 -/ -- ([0, 1], [8, 9])
#eval test "Åℬℭⅆⅇⅈⅉ"    /- 3 byte UTF8 -/ -- ([Å, ℬ], [­, ⅆ]) -- ℭ got garbled because it got chopped in half by seek
#eval test "𝔸𝔹ℂ𝔻"      /- 4 byte UTF8 -/ -- ([𝔸, 𝔹], [ℂ, 𝔻])
```

**Comment by digama0** [comment]
Without looking at the code, here is what I think is happening. io.fs.read accepts a length argument, but this is in characters not bytes, so when calculating how big the buffer needs to be to hold n characters, it uses 4*n as an upper bound. So a read of 4*n bytes is sent to the lower level and the buffer gets filled, then it is parsed to find out how many characters are actually in the text and discards everything after the nth character. But the lower level has at this point successfully returned a byte block of 4*n characters, so the read cursor moves forward by this much and on the next read the discarded characters are not recovered.

To fix this, we either need to call seek on the lower level (which may not be possible), or we have to keep a pushback buffer containing characters that we want to unread after overshooting the character count.

**Comment by Kha** [comment]
Exactly, this `fseek` is probably failing on pipes: https://github.com/leanprover-community/lean/blob/303d31f1f1e4af8727761098b43dbe59d7c67d64/src/library/vm/vm_io.cpp#L378

**Comment by digama0** [comment]
Apparently, you can set binary mode (it is an optional parameter in `mk_file_handle`) and then all characters are 1 byte. So this might be a suitable workaround for your use case @jasonrute . Although, I can't find any way to set this on the stdio handle of a child (during or after creation), so we might have to add a hook for that.

**Comment by digama0** [comment]
Ah, they appear to be hardcoded to text mode here:

https://github.com/leanprover-community/lean/blob/303d31f1f1e4af8727761098b43dbe59d7c67d64/src/library/process.cpp#L364-L367
