### ISSUE TITLE
fix build for sockets

### ISSUE THREAD

**Issue by cipher1024** [leanprover-community/lean#28]
Merging the sockets PR broke the build https://travis-ci.org/leanprover-community/lean/builds/523525562. @khoek Please fix it

**Comment by khoek** [comment]
@cipher1024 Is there a way for you to re-run it? It looks to me like the mac jobs didn't even start compiling, and it built fine on Travis on my branch, so maybe Travis just died?

**Comment by khoek** [comment]
See #30, I think it's fine

**Comment by khoek** [comment]
https://travis-ci.org/leanprover-community/lean/builds/523525562

It's fine, travis's fault.

**Comment by khoek** [comment]
Close?
