### ISSUE TITLE
"comment-like" input for string literals

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/lean#351]
https://github.com/leanprover-community/mathlib/issues/3088 made me start thinking about (yet another) refactor of tactic doc input. Suppose that we came up with a list of fields that every tactic doc entry should have: "summary," "syntax," "examples," etc. It would be nice to make these a semantic part of the tactic doc entry object, instead of just headers in a markdown block. One advantage to this: they can't be omitted. Another advantage: pieces can be embedded in other texts automatically. E.g. if MIL wanted to introduce the syntax for `linarith`, it could easily grab only the "syntax" field of the `linarith` doc entry.

An issue here is that we'd have to give these different fields as strings. Right now, we use doc strings on declarations/commands to parse declarations, so that we get nicer formatting, don't have to escape quotes, etc. This doesn't work so well if multiple strings are involved.

So, feature request: is it plausible to introduce an alternate way to parse string literals, that behaves effectively the same as comments/doc strings? Not having to escape quotes is a must; markdown-aware formatting in VS Code is nice but not essential.

**Comment by gebner** [comment]
Can you please suggest a syntax?  Ideally the literals would begin with `/-` and end with `-/` so that they can be nested in comments (and vice versa).

Syntax highlighting should be no problem.
