### ISSUE TITLE
`injection` introduces too many pis

### ISSUE THREAD

**Issue by JLimperg** [leanprover-community/lean#400]
`injection` introduces not only the equations it generated but all pis in the target. I find this counterintuitive, especially when using `injection with ...`. Example:

```lean
example (n m k : ℕ) (h : n + 1 = m + 1) : m = k → n = k :=
begin
  injection h with x y z,
  /- actual goal:
     n m k : ℕ
     h : n + 1 = m + 1
     x : n = m
     y : m = k
     ⊢ n = k

     expected goal:
     n m k : ℕ
     h : n + 1 = m + 1
     x : n = m
     ⊢ m = k → n = k

     Nb: we could also clear h:
     n m k : ℕ
     h : n = m
     ⊢ m = k → n = k
  -/
  sorry
end
```

If you agree, I can refactor `injection` to introduce only the equations it generated.

**Comment by gebner** [comment]
Seems reasonable to me, if you're not sure please also ask on zulip.
