### ISSUE TITLE
by_contra should use classical reasoning

### ISSUE THREAD

**Issue by lambda-fairy** [leanprover-community/lean#433]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

In #409, the `by_cases` tactic was changed to use classical reasoning and not require `decidable`. For consistency I think we should update `by_contra` / `by_contradiction` to do the same.

### Steps to Reproduce

```
example : (id : ℕ → ℕ) = λ x, x :=
begin
  by_contra,
  exact a rfl,
end
```

**Expected behavior:** Proof is accepted.

**Actual behavior:**

```
tactic by_contradiction failed, target is not a negation nor a decidable proposition (remark: when 'local attribute [instance] classical.prop_decidable' is used, all propositions are decidable)
state:
⊢ id = λ (x : ℕ), x
```

**Reproduces how often:** 100%

### Versions

Lean (version 3.18.4, commit f539be1e867c), [web editor](https://leanprover-community.github.io/lean-web-editor/)

**Comment by bryangingechen** [comment]
Fixed in https://github.com/leanprover-community/lean/commit/af2f0be9958b0bc390698ffad434c2305ab40e0f, thanks!
