### ISSUE TITLE
typeclass resolution fails for `get` from option_t state_t

### ISSUE THREAD

**Issue by ammkrn** [leanprover-community/lean#460]
This example works on 3.4.2 (installed via elan) assuming there's an instance of has_repr id A :
```
def ex1 : option_t (state_t string id) string :=
  do
    s <- get,
    option_t.mk $ return s

#eval ex1.run.run "an example" 
-- ((some "an example"), "an example")
```

but fails using 3.19.0 installed via leanproject with the following error:
maximum class-instance resolution depth has been reached (the limit can be increased by setting option 'class.instance_max_depth') (the class-instance resolution trace can be visualized by setting option 'trace.class_instances')

**Comment by bryangingechen** [comment]
I did some bisection and your example works in 3.6.1c but fails in 3.7.1c. Maybe you can figure out which change broke your example from [the changelog for 3.7.0c](https://github.com/leanprover-community/lean/blob/master/doc/changes.md#v370c-13-mar-2020)?

**Comment by ammkrn** [comment]
Thanks. It's almost certainly `Type class resolution solves instance arguments from right-to-left (#139)`. Looking at the PR for #139, it looks like there was a bunch of explicit swapping of typeclass arguments (including `monad_reader_trans`), but `monad_state_trans` escaped unflipped.

**Comment by bryangingechen** [comment]
Cool! Do you mind making a PR?

**Comment by ammkrn** [comment]
You got it. Thanks for the help in figuring that out.
