### ISSUE TITLE
Generated documentation is empty

### ISSUE THREAD

**Issue by fischerman** [leanprover-community/lean#51]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The file generated by the command line argument `--doc` is empty.

### Steps to Reproduce

1. Create file `doc.lean` with some doc strings.
```
namespace test

/-- docs for the win! -/
lemma abc : true := true.intro

end test
```
2. Run `lean --doc=doc.out doc.lean`
3. Check that `doc.out` is empty

**Expected behavior:** `doc.out` should contain some documentation?

**Reproduces how often:** Always

### Versions

Lean (version 3.4.2, commit cbd2b6686ddb, Release)
on Ubuntu 18.04 x64

**Comment by Vtec234** [comment]
So what you tried here isn't actually a doc - `/- -/` is just a comment, completely ignored by the parser. The syntax for doc strings is `/-- -/` (with two dashes), but they only work on some commands. For example: definitions, lemmas, inductive types. You cannot put one on a namespace AFAIK. There is also a syntax for module documentation, `/-! -/`.

However, even when using correct syntax I can't make Lean produce any documentation output, so this still looks like a bug.

**Comment by fischerman** [comment]
Thanks! I've updated the issue description. I can confirm that it still does not work.

**Comment by digama0** [comment]
This isn't so much a bug as a completely missing feature. AFAIK it's never been developed beyond the --doc stub.
