### ISSUE TITLE
Crash related to revert

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/lean#53]
Reported by @Vtec234 on [Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/Lean.20segfaulting/near/168061695). The following code crashes both 3.4.2 and the latest 3.5.0c nightly ("nightly-2019-05-17"):
```lean
lemma segfault {α: Type u} {a a': α} (H : a = a') : a = a' := begin
  revert a a,
end
```
This does not crash when [run in the web editor](https://bryangingechen.github.io/lean/lean-web-editor/#code=universe%20u%0A%0Alemma%20segfault%20%7B%CE%B1%3A%20Type%20u%7D%20%7Ba%20a%27%3A%20%CE%B1%7D%20%28H%20%3A%20a%20%3D%20a%27%29%20%3A%20a%20%3D%20a%27%20%3A%3D%20begin%0A%20%20revert%20a%20a%2C%0Aend).

**Comment by bryangingechen** [comment]
The crash occurs because `m_user_name2idxs.find` returns a null pointer here: https://github.com/leanprover-community/lean/blob/master/src/library/local_context.cpp#L189

Would it make sense to just have `erase_user_name` return immediately if `m_user_name2idxs.find` is null?

(This code was removed in Lean 4 in this commit: https://github.com/leanprover/lean4/commit/69070f43eb1339e1824cac77d676c5db88b4fec7#diff-8e1b5fb692d035eb36593afedf77385f)

**Comment by cipher1024** [comment]
I wouldn't go this deep. I think `revert_lst` should check that the variables exist when reverting them

**Comment by cipher1024** [comment]
(I have recent commit that does similar things)

**Comment by bryangingechen** [comment]
Sounds good; I think I see something reasonable to PR when I’m back with my Lean computer.

**Comment by bryangingechen** [comment]
(Namely, I want to skip over duplicates in this loop: https://github.com/leanprover-community/lean/blob/ec1613aef1eee72e601f192b16740629c6d49690/src/library/tactic/revert_tactic.cpp#L36)

**Comment by cipher1024** [comment]
I'm not sure if it's worth getting through the trouble of skipping duplicates. I think reporting an error is better. It has the nice property that `revert_lst (xs ++ ys) = revert_lst xs >> revert_lst ys` (if you ignore the return value, otherwise, the rhs is `(+) <$> revert_lst xs <*> revert_lst ys`, which is also nice, albeit a bit more complicated)

**Comment by bryangingechen** [comment]
OK, we can certainly throw an error, but I think we still have to do duplicate detection, right? Otherwise we’ll have to make deeper changes. I might be missing an easier way to test for this though.

**Comment by cipher1024** [comment]
We still have to do duplicate detection. I was just saying that throwing an error will probably be simpler than removing duplicates.
