### ISSUE TITLE
First example in documentation doesn't work in Firefox

### ISSUE THREAD

**Issue by David263** [leanprover-community/lean#536]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

The Lean introductory documentation appears to be https://leanprover.github.io/introduction_to_lean/. At the beginning is a button labeled "Try it yourself". It doesn't seem to work for me in Windows/Firefox, latest stable versions. It appears at first to work in Windows/Chrome, but then it fails there too.

### Steps to Reproduce

1. Open the above page in Firefox.
2. Click the button described above.

**Expected behavior:** [What you expect to happen]

Expected to see "hello world".

**Actual behavior:** [What actually happens]

Got error messages:

1:0:error: file '/library/init/wf.lean' not found
1:0:error: invalid import: init
could not resolve import: init
1:0:info: "hello world!" : string
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
1:0:error: file '/library/init/wf.lean' not found
Done(0.008sec)
-- Done(0.014sec)

**Reproduces how often:** [What percentage of the time does it reproduce?]

5 times out of 5.

### Versions

(Unknown)

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

(Attempt to do this failed.)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by bryangingechen** [comment]
Hi and welcome! For resources on Lean 3, I would recommend starting with those on the community page instead: https://leanprover-community.github.io/learn.html

I'm closing this issue because the "leanprover-community" organization on GitHub has no control over the pages you linked, which are run by the official Lean devs (the "leanprover" organization). My understanding is that the old "introduction to Lean" pages are effectively abandoned, which is why no links to them exist from [the official Lean webpage](https://leanprover.github.io/documentation/).

If you have more questions feel free to join our Zulip [here](https://leanprover.zulipchat.com/).

**Comment by bryangingechen** [comment]
My apologies, I didn't see that you were directed here by @jcommelin from https://github.com/leanprover/lean4/issues/315.

However, what I said above still holds true.

**Comment by jcommelin** [comment]
Oops, sorry for the incorrect redirect...
@Kha I'll leave it up to you whether you regard this as "wontfix" or whether you want to do something with it in the lean 3 repo.

**Comment by Kha** [comment]
For the record, the concerned repo has been archived and made private, but apparently the `gh-pages` branch is still served. @leodemoura We might want to temporarily unarchive and add a warning to or outright delete the branch at some point.
