### ISSUE TITLE
cases segfaults when seeing fin.last

### ISSUE THREAD

**Issue by gebner** [leanprover-community/lean#578]
```lean
def fin.last (n : ℕ) : fin (n+1) := ⟨_, n.lt_succ_self⟩
example (i_val : ℕ) (i_property : i_val < 1)
  (h : (⟨i_val, i_property⟩ : fin _) = fin.last 0) : false :=
by cases h
```

**Comment by kbuzzard** [comment]
Wow! How come this wasn't discovered years ago?

**Comment by gebner** [comment]
Good question!  The bug is not limited to subtypes either, any equality of constructors where one of the field types is a prop will cause this.  Maybe cases is not the first tactic to reach for when you see an equality?
