### ISSUE TITLE
`lean --tlean` uses excessive memory

### ISSUE THREAD

**Issue by semorrison** [leanprover-community/lean#647]
Running `lean --tlean` on mathlib uses in excess of 64gb of RAM. Both `lean --export` and `lean --ast` complete without going above 10gb.

This is currently an obstacle for doing CI on `mathport`. If anyone wants to have a look in the `--tlean` export code to see if they can identify a problem that would be very helpful. Alternatively Mario [suggested on zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/memory.20usage.20with.20.60lean.20--ast.20--tlean.60) that `mathport` could be made to work with just the `--ast` output.

**Comment by gebner** [comment]
Fixed by #648.

**Comment by semorrison** [comment]
Fantastic. Looks like it now takes ~30gb.
