### ISSUE TITLE
calc tactic resolves notation incorrectly

### ISSUE THREAD

**Issue by eric-wieser** [leanprover-community/lean#651]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

`calc`, the tactic, is confused by a local variable called `eq`.

### Steps to Reproduce

```lean
example (eq : ℕ) : 1 = 1 :=
begin
  calc 1 = 1 : rfl
     ... = 1 : rfl,
end
```
**Expected behavior:** No diagnostics

**Actual behavior:** `invalid occurrence of field notation`

**Reproduces how often:** Always

### Versions

Lean (version 3.35.1, commit 4887d8a30621, Release)

**Comment by eric-wieser** [comment]
I think this is the start of the offending code:

https://github.com/leanprover-community/lean/blob/e4203af8b09450ceebc3b44f767e37a96ef47402/src/frontends/lean/tactic_notation.cpp#L285-L290

**Comment by digama0** [comment]
I believe the issue is in the quoting and antiquoting that occurs when translating the calc proof to a pexpr to pass to refine. The `calc` part elaborates to the equivalent of:

```lean
example (eq : ℕ) : 1 ≤ 1 :=
by tactic.interactive.refine ``(@eq.trans _ 1 1 1 rfl rfl)
```
which fails because you can't write `@eq.trans` when `eq` is a local variable (which seems like an issue all on its own, but probably for another day). Using `calc` directly doesn't have this issue because it directly generates an ``expr.const `eq.trans`` which can't be misinterpreted.

**Comment by digama0** [comment]
This is also visible as a difference in how expr vs pexpr quoting is handled:
```lean
example (eq : ℕ) : 1 = 1 :=
by exact %%`(@eq.trans _ 1 1 1 rfl rfl) -- ok, uses global eq.trans

example (eq : ℕ) : 1 = 1 :=
by exact %%``(@eq.trans _ 1 1 1 rfl rfl) -- fail, tries to project on the local variable
```
