### ISSUE TITLE
`simp [has_zero.zero]` loops(?)

### ISSUE THREAD

**Issue by JasonGross** [leanprover-community/lean#74]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

```lean
example : (0 : ℤ) = 0 :=
begin
  simp [has_zero.zero]
-- 4:1: (deterministic) timeout
end
```

**Expected behavior:** lean returns quickly

**Actual behavior:** lean times out

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Versions

```
$ lean --version
Lean (version 3.4.2, commit cbd2b6686ddb, Release)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
$ uname -a
Linux jgross-Leopard-WS 4.4.0-161-generic #189-Ubuntu SMP Tue Aug 27 08:10:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Vtec234** [comment]
For me on nightly Lean (`Lean (version 3.5.0, nightly-2019-10-01, commit 6ed0977fcbc1, Release)
`) this works fine (goal is proven). This could be purely accidental, though. Does that example still timeout for you when placed in a clean file with nothing else in it?

**Comment by JasonGross** [comment]
Hmmm, it seems to work fine now.  Maybe there was left-over state from the other file I was using?  I did try this in a file all on its own, but not from the command line, before.  (I'm using the emacs lean-mode.)
