### ISSUE TITLE
Why doesn't this repository contain Lean 4 ?

### ISSUE THREAD

**Issue by yurivict** [leanprover-community/lean#768]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
[This tutorial](https://leanprover.github.io/functional_programming_in_lean/title.html) talks about Lean 4, but this repository contains Lean 3.x

Why isn't Lean 4 imported here?

**Comment by fpvandoorn** [comment]
You're looking for https://github.com/leanprover/lean4.
The [mathematical library of Lean](https://github.com/leanprover-community/mathlib) has not been ported to Lean 4 yet, although we are making a lot of progress in the porting process, and this is the version of Lean that supports the mathematical library.

**Comment by yurivict** [comment]
When is Lean 4 expected to become fully functional and replace Lean 3?

**Comment by jcommelin** [comment]
As a programming language, it already is. But if you are interested in formalization of mathematics, then it makes sense to wait till mathlib has been ported to Lean 4. This will probably happen in the next few months.
