### ISSUE TITLE
Documentation for regular installation links to installation for lean4

### ISSUE THREAD

**Issue by rommeswi** [leanprover-community/lean#814]
### Prerequisites

None

### Description

I want to install lean 3.xxx because lean 4 is still a mess for Emacs.
I came to this repository and tried to follow the instructions for installation.
I ended up with installation instructions to install lean 4, not 3.

### Steps to Reproduce

1. Clicking "these instructions under Regular install" and "Debian/Ubuntu" leads to:
2. https://leanprover-community.github.io/install/debian.html

**Expected behavior:**

Correct installation instructions for lean 3.

**Actual behavior:** 
Installation instructions to install lean 4.

**Reproduces how often:**
100% (also when choosing other operating systems)

### Versions

Current git repo

**Comment by PatrickMassot** [comment]
Thanks for you comment. We updated the README and created OLD_README.md with links to the deprecated Lean 3 website. 

I encourage you to open issues to the Lean 4 emacs mode repository because sticking to Lean 3 has no future at all.
