### ISSUE TITLE
Recent gcc versions can't build lean on IA32

### ISSUE THREAD

**Issue by vvs-** [leanprover-community/lean#84]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description
I was unable to build Lean on i686 architecture using gcc versions > 6.5.0. This looks definitely like gcc bug so it's unclear if Lean developers could do something about it. Those gcc versions could be blacklisted on 32-bit architecture, though. That would make life of ordinary users and Linux packagers easier.

### Steps to Reproduce

1. Use any gcc version greater than 6.5.0.

**Expected behavior:**

**Actual behavior:**
```
/bin/ld: shared_test: hidden symbol `__divmoddi4' in /lib/gcc/i686-unknown-linux-gnu/7.4.0/libgcc.a(_divmoddi4.o) is referenced by DSO
```

**Reproduces how often:**
I've tried gcc 6.5.0, 7.4.0 and 8.3.0. Only gcc 6.5.0 works fine.

### Versions
Lean 3.4.2 and `master` (3.5.0). I'm on NixOS 19.03 i686.

### Additional Information
Also, I don't know how critical this `shared_test` is. If possible it could be skipped on 32-bit.

**Comment by cipher1024** [comment]
Is there a reason to use two particular compilers?

**Comment by vvs-** [comment]
These were versions already packaged in NixOS. There are even more, but I don't see much benefit in testing gcc 4.9 or different version of Clang. The goal was to build Lean on 32-bit architecture, so at least one gcc version should be sufficient.

That's one of the advantages of using NixOS in the first place: every application has its own set of dependencies, compilers included, because every build is isolated. It's resilient to breakage due to incompatibilities in different versions of libraries and tools.

**Comment by cipher1024** [comment]
This is a Nix issue https://github.com/NixOS/nixpkgs/issues/36947

**Comment by vvs-** [comment]
To be fair the issue referenced above is not the actual cause here. There is something else. But probably this is not Lean's concern after all.
