### ISSUE TITLE
Server crash when editing files ending in "." + newline

### ISSUE THREAD

**Issue by bryangingechen** [leanprover-community/lean#85]
Create a new file in a Lean 3.4.2 or Lean 3.5.0 project with the following contents:
```lean
.
```
Open the file in VS Code and then add a new line after the period and the Lean server will crash. I'm also able to trigger a crash by simply moving the cursor around.

This seems to happen for any file ending in a period.

I've been unable to reproduce this from the command line. Can anyone check if this happens in Emacs as well?

First reported in Zulip by @alashworth [here](https://leanprover.zulipchat.com/#narrow/stream/113489-new-members/topic/Beginner.20question.3A.20inequality/near/177331714).

**Comment by cipher1024** [comment]
Emacs doesn't crash on this situation

**Comment by gebner** [comment]
@cipher1024 Does emacs maybe automatically add a newline at the end?

**Comment by bryangingechen** [comment]
I have the "Files: Insert Final Newline" setting turned on in VS Code. When
I turn that off and work with a file ending with a `.` character with no
newline, then I can't trigger a crash. Similarly, if I work with a file
ending with `.` and more than 1 newline, I also can't seem to get a crash.
The Lean server seems to crash only with a file ending with . and then
possibly some white space and then a single newline.

**Comment by bryangingechen** [comment]
OK, I ran a debug build of Lean 3.5.0 and got the following message after adding a newline to a file ending in `.`:
>LEAN ASSERTION VIOLATION
>File: /.../lean/lean/src/frontends/lean/scanner.cpp
>Line: 47
> Task: :
> m_curr != Eof

[Here's a link to that line in this repo](https://github.com/leanprover-community/lean/blob/master/src/frontends/lean/scanner.cpp#L47). I probably won't have time to dig further into this until the weekend, so if anyone sees how to fix this, they should go ahead and PR it or post some hints here.

**Comment by cipher1024** [comment]
@gebner I disabled it and got the same behavior. 

@bryangingechen It is really odd that my server doesn't crash in that situation

**Comment by bryangingechen** [comment]
Here's a way to trigger the crash from the command line. Run `lean --server` and then first paste in this line and hit enter:
```json
{"command":"sync","file_name":"test.lean","content":".\n","seq_num":0}
```
After the server finishes responding, paste in this line and hit enter:
```json
{"command":"info","file_name":"test.lean","line":2,"column":0,"seq_num":1}
```
I get a segmentation fault shortly afterwards with either Lean 3.4.2 or the non-debug build of Lean 3.5.0 nightly-2019-11-15 (lldb trace below). In the debug build I get the assertion violation, but no crash.

Strangely, if I paste the two lines above together (with a newline separating them) and then press enter, then I don't get a crash. If I paste in a longer snippet like this:
```json
{"command":"sync","file_name":"test.lean","content":".\n","seq_num":0}
{"command":"info","file_name":"test.lean","line":2,"column":0,"seq_num":1}
{"command":"info","file_name":"test.lean","line":2,"column":0,"seq_num":2}
{"command":"info","file_name":"test.lean","line":2,"column":0,"seq_num":3}
```
Then sometimes I see `{"message":"unknown exception","response":"error","seq_num":1}`, but still no crash. I see the same behavior if I save the above snippet as `test.json` and run `lean --server=test.json`.

Here's a copy+paste from an lldb session where I triggered the crash in Lean 3.4.2:

```
{"command":"sync","file_name":"test.lean","content":".\n","seq_num":0}
{"is_running":false,"response":"current_tasks","tasks":[]}
{"is_running":false,"response":"current_tasks","tasks":[]}
{"message":"file invalidated","response":"ok","seq_num":0}
{"is_running":true,"response":"current_tasks","tasks":[{"desc":"parsing at line 1","end_pos_col":1,"end_pos_line":2,"file_name":"test.lean","pos_col":0,"pos_line":1}]}
{"is_running":false,"response":"current_tasks","tasks":[]}
{"command":"info","file_name":"test.lean","line":2,"column":0,"seq_num":1}
Process 36606 stopped
* thread #3, stop reason = EXC_BAD_ACCESS (code=1, address=0x181a298f1)
    frame #0: 0x00000001005852f6 lean`lean::scanner::next() + 70
lean`lean::scanner::next:
->  0x1005852f6 <+70>: movb   (%rcx,%rax), %al
    0x1005852f9 <+73>: cmpb   $-0x1, %al
    0x1005852fb <+75>: je     0x10058530a               ; <+90>
    0x1005852fd <+77>: jmp    0x10058530c               ; <+92>
Target 0: (lean) stopped.
(lldb) bt
* thread #3, stop reason = EXC_BAD_ACCESS (code=1, address=0x181a298f1)
  * frame #0: 0x00000001005852f6 lean`lean::scanner::next() + 70
    frame #1: 0x0000000100588388 lean`lean::scanner::skip_to_pos(std::__1::pair<unsigned int, unsigned int> const&) + 88
    frame #2: 0x00000001006ecc17 lean`lean::module_parser::resume(lean::module_parser_result const&, lean::optional<std::__1::vector<std::__1::shared_ptr<lean::gtask_cell>, std::__1::allocator<std::__1::shared_ptr<lean::gtask_cell> > > > const&) + 55
    frame #3: 0x00000001000190ff lean`lean::parse_breaking_at_pos(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<lean::module_info const>, std::__1::pair<unsigned int, unsigned int>, bool) + 623
    frame #4: 0x0000000100019cb9 lean`lean::server::info(std::__1::shared_ptr<lean::module_info const> const&, std::__1::pair<unsigned int, unsigned int> const&) + 89
    frame #5: 0x0000000100023bec lean`lean::task_builder<lean::server::cmd_res>::base_task_imp<lean::server::handle_info(lean::server::cmd_req const&)::$_3>::execute(void*) + 44
    frame #6: 0x0000000100236962 lean`lean::library_scopes_imp::execute(void*) + 82
    frame #7: 0x0000000100040d80 lean`lean::cancellable_task_imp::execute(void*) + 48
    frame #8: 0x0000000100023ad4 lean`lean::task_cell<lean::server::cmd_res>::execute() + 180
    frame #9: 0x0000000100040733 lean`lean::task_queue::execute(std::__1::shared_ptr<lean::gtask_cell> const&) + 451
    frame #10: 0x0000000100234195 lean`std::__1::__function::__func<lean::mt_task_queue::spawn_worker()::$_2, std::__1::allocator<lean::mt_task_queue::spawn_worker()::$_2>, void ()>::operator()() + 645
    frame #11: 0x000000010003d3a0 lean`lean::lthread::imp::_main(void*) + 32
    frame #12: 0x00007fff781ce2eb libsystem_pthread.dylib`_pthread_body + 126
    frame #13: 0x00007fff781d1249 libsystem_pthread.dylib`_pthread_start + 66
    frame #14: 0x00007fff781cd40d libsystem_pthread.dylib`thread_start + 13
```

I guess the crash occurs due to bounds violation in scanner.cpp [here](https://github.com/leanprover-community/lean/blob/806a4c57d552b3b70aac83cadf473ef6128eaecb/src/frontends/lean/scanner.cpp#L57) but I haven't figured out how exactly this occurs...
