### ISSUE TITLE
implement `#where` in c++

### ISSUE THREAD

**Issue by robertylewis** [leanprover-community/lean#90]
I added docs for mathlib's `#where` command today, and it occurred to me that it should really be implemented natively in 3.5c. The current version gives a reasonable approximation of the info you want to see, but it's not really reliable. Even if we don't move mathlib to 3.5c (I think we should soon), it's a transient command, so it wouldn't break anything.

(I'm not planning to implement this myself, but it might be a nice little project if anyone is interested.)

### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already [filed](https://github.com/leanprover-community/lean/issues).
        * Specifically, check out the [wishlist](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AI-wishlist), open [RFCs](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3ARFC),
        or [feature requests](https://github.com/leanprover-community/lean/issues?q=is%3Aissue+is%3Aopen+label%3AFeature).
    * Reduced the issue to a self-contained, reproducible test case.

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `lean --version`,
please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by gebner** [comment]
@cipher1024 Did your PR #192 fix this issue?

**Comment by bryangingechen** [comment]
This was (mostly) done by @khoek in https://github.com/leanprover-community/mathlib/pull/2465. There's one last issue which is tracked in #196.
